@startuml
!theme hack
title GunBroker Sniper CLI Process
header Automated gunbroker auctions
footer Snipe Smarter

|BG|
if (process running) then (yes)
	:quit;
	stop
endif
:Check info store;
|CLI|
:Disp Ascii Header;
|BG|
if (info saved) then (yes)
	:retrieve info;
else (no)
	|CLI|
	:Prompt for login information;
	|BG|
	:Login;
	:goto item;
	if (item exists) then (yes)
		:acquire info;
		:save info to store;
		|CLI|
		:Disp retrieved info;
		|BG|
	else (no)
		:error;
		Kill
	endif
endif
|CLI|
:Disp Remaining time;
|BG|
:set cron;
|CLI|
:Disp Timer till snipe;
|BG|
repeat :sleep;
repeat while (time) is (no)
:goto page;
@enduml
