@startuml
'https://plantuml.com/activity-diagram-beta
!theme cerulean-outline
title GunBroker Sniper
header A sniper for gunbroker auctions
footer shooting for the smarter

actor dude [
	Title: The Dude
	===
	Lang: Grunts
]
rectangle localhost{
	node python [
		Title: Python 3.9
		===
		File: main.py
		---
		Facility: Main source code
	]
	node geckodriver [
		Title: geckodriver
		===
		Lang: Local system install
		---
		Facility: Headless Webdriver
	]
	node selenium [
		Title: Selenium
		===
		Type: Python Module
		---
		Facility: Translate directions to geckodriver
	]
	node captcha_buster [
		Title: Buster: Captcha Solving for Humans
		===
		Form: Firefox Extension
		---
		Facility: Resolve Captcha Challenges
	]
}
cloud gunbroker{
	frame recaptchav2 [
	Title: Recaptcha V2
	===
	Lang: JavaScript
	---
	Notes: Interfaces with Google's Recaptcha API
	]
	artifact item [
	TITLE: Desired Item
	===
	Lang: Pew-Pew
	]
}
'dude --> sel_view
'sel_view ~~> geckodriver : ""Magic""
dude --> python
python ~~> selenium
selenium --> geckodriver
geckodriver ~~> item : ""HTTP Request""
geckodriver ~~> captcha_buster
captcha_buster <-- recaptchav2 : ""HTTP Response""


@enduml
