@startuml
'https://plantuml.com/activity-diagram-beta
!theme cerulean-outline
title GunBroker Sniper
header A sniper for gunbroker auctions
footer shooting for the smarter

actor dude [
	Title: The Dude
	===
	Lang: Grunts
]
rectangle localhost{
	node python [
		Title: Python 3.10
		===
		File: main.py
		---
		Facility: Main source code
	]
	node geckodriver [
		Title: geckodriver
		===
		Lang: Docker Image
		---
		Facility: Dockerized Headless WebDriver
	]
	node selenium [
		Title: Selenium
		===
		Type: Python Module
		---
		Facility: Translate directions to geckodriver
	]
	node captcha_bypass [
		Title: Captcha_Bypass
		===
		Lang: Python
		---
		Notes: requires sitekey and domain to run in docker
		....
		But will receive separate instructions from cloud proxy
	]
}
cloud gunbroker{
	frame recaptchav2 [
	Title: Recaptcha V2
	===
	Lang: JavaScript
	---
	Notes: Interfaces with Google's Recaptcha API
	]
	artifact item [
	TITLE: Desired Item
	===
	Lang: Pew-Pew
	]
}
'dude --> sel_view
'sel_view ~~> geckodriver : ""Magic""
dude --> python
python ~~> geckodriver
selenium --> geckodriver : ""Docker Socket""
geckodriver ~~> item : ""HTTP Request""
geckodriver ~~> captcha_bypass : "DNS Proxy"
captcha_bypass <-- recaptchav2 : ""HTTP Response""


@enduml
